site_name: OpInt FW Docs
site_description: Documentation of the Operational Intelligence Framework.
site_author: OpInt FW Developers
site_url: https://opint-fw-docs.web.cern.ch/

repo_name: GitHub
repo_url: https://github.com/operationalintelligence/opint-framework-docs
edit_uri: 'blob/master/docs'

theme:
    name: material

nav:
    - Introduction: index.md
    - Installation: install.md
    - 'Core Components':
        - 'Feedback mechanism': core_components/feedback.md
        - 'Scheduler': core_components/scehduler.md
        - 'DataLoaders':
            - 'BaseLoader': core_components/data_loader.md
            - 'HDFSLoader': core_components/data_loader_hdfs.md
        - 'API': core_components/index.md
    - 'Example app':
          - 'App structure': core_components/index.md
    - 'MkDocs official documentation': https://www.mkdocs.org/
    - 'GitHub Repo': https://github.com/operationalintelligence/opint-framework